#spring:
#  activemq:
#    broker-url: tcp://172.0.15.82:61616
#    user: admin
#    password: admin
#  jms:
#    pub-sub-domain: true  #false=queue 队列 | true=topic 主题
#
##自己定义队列名称
#myqueue: boot-activqmq-queue
#
##自己定义主题名称
#mytopic: boot-activqmq-topic